"""Pydantic models generated from apps/api/openapi.json.

This file is regenerated by scripts/generate-python-contracts.py.
Do not edit by hand; the CI drift check will fail.
"""

# No schemas were present in the OpenAPI spec when last generated.
