// Generated by `pnpm generate` in @mimir/contracts.
// This stub exists until the API OpenAPI spec is first exported.
export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export type components = Record<string, never>;
export type $defs = Record<string, never>;
