#!/usr/bin/env python3
"""Generate Pydantic models from the OpenAPI spec.

This script is the Python-side counterpart to packages/contracts/generate.
It must consume the same apps/api/openapi.json source of truth so TS and Python
share one contract. Run it after regenerating openapi.json.
"""

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OPENAPI = ROOT / "apps" / "api" / "openapi.json"
OUTPUT = ROOT / "services" / "shared" / "src" / "mimir_shared" / "generated_models.py"

EMPTY_FILE = '''"""Pydantic models generated from apps/api/openapi.json.

This file is regenerated by scripts/generate-python-contracts.py.
Do not edit by hand; the CI drift check will fail.
"""

# No schemas were present in the OpenAPI spec when last generated.
'''


def main() -> int:
    if not OPENAPI.exists():
        print(f"OpenAPI spec not found: {OPENAPI}", file=sys.stderr)
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    cmd = [
        "python",
        "-m",
        "datamodel_code_generator",
        "--input",
        str(OPENAPI),
        "--output",
        str(OUTPUT),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.11",
        "--use-schema-description",
        "--reuse-model",
        "--collapse-root-models",
        "--use-title-as-name",
    ]

    print(f"Generating Python models from {OPENAPI}...")
    result = subprocess.run(cmd, check=False, capture_output=True, text=True)
    if result.returncode == 0:
        print(f"Python models written to {OUTPUT}")
        return 0

    if "No schemas found" in result.stderr or "Models not found" in result.stderr:
        OUTPUT.write_text(EMPTY_FILE, encoding="utf-8")
        print(f"No schemas in OpenAPI spec; wrote placeholder to {OUTPUT}")
        return 0

    print(result.stderr, file=sys.stderr)
    print("datamodel-code-generator failed", file=sys.stderr)
    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
